org: scoobies
service: playlist-backend
frameworkVersion: "4"

provider:
  name: aws
  stage: prod
  region: ap-south-1
  runtime: nodejs24.x

  environment:
    CURRENT_AWS_REGION: ap-south-1
    TABLE_NAME: playlist-backend-data-table
    BUCKET_NAME: playlist-backend-assets-bucket
    CLOUDFRONT_DOMAIN:
      Fn::GetAtt:
        - PlaylistBackendCloudFrontDistribution
        - DomainName

  iam: ${file(aws/iam.yaml)}

build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node24
    platform: node
    banner:
      js: "import { createRequire } from 'node:module'; const require = createRequire(import.meta.url);"

plugins:
  - serverless-offline

functions:
  storageApi:
    handler: src/storage/handler.handler
    events:
      - httpApi:
          path: /storage
          method: ANY
      - httpApi:
          path: /storage/{proxy+}
          method: ANY

  tracksApi:
    handler: src/tracks/handler.handler
    events:
      - httpApi:
          path: /tracks
          method: ANY
      - httpApi:
          path: /tracks/{proxy+}
          method: ANY

resources: ${file(aws/resources.yaml)}
